//list of subjects
var subjects = new Array(
"Justin Bieber",
"ears",
"kittens",
"chimps",
"pigeons",
"custard",
"turtles",
"the grim reaper",
"cheese graters",
"venus fly traps",
"zombies",
"pirates",
"knitwear",
"manbags",
"frying pans",
"penguins",
"zen monks",
"scarecrows",
"prosthetic limbs",
"puppets",
"snowmen",
"milkmen",
"socks",
"underwear",
"Morrisey",
"pickels",
"rain",
"the sun",
"ants",
"mops",
"cupcakes",
"traingles",
"xylophones",
"maraccas",
"motorcycles",
"soufflés",
"meat butchers",
"dentists",
"skirts",
"volcanoes",
"fish",
"sandals",
"ducks",
"jellyfish",
"grannies",
"chess pieces",
"surfboards",
"evangelists",
"rugby balls",
"chalkboards",
"artichokes",
"alsatians",
"feathers",
"sequin dresses",
"bottoms",
"lesbians",
"axe murderers",
"axes",
"elbow patches",
"china dolls",
"mutants",
"braces",
"dungarees",
"calamari",
"pineapples",
"mirangues",
"tapioca",
"corkscrews",
"ironing boards",
"feather dusters",
"peking duck",
"suspenders",
"ninjas",
"left socks",
"collanders",
"Kim Jong-il",
"dreadlocks",
"sandy beaches",
"sandy beaches",
"Myley Cyrus",
"Jesus",
"nymphomaniacs",
"pyromaniacs",
"scientologists",
"octopus",
"cufflinks",
"stick men",
"shoe laces",
"sewage systems",
"bulldogs",
"speed bumps",
"poodles",
"siberian hamsters",
"siamese twins",
"unicorns",
"kebabs",
"quiffs",
"milkshakes",
"mojitos",
"guacamole",
"carp",
"strip clubs",
"tin foil",
"aliens",
"palm trees",
"coconuts",
"pharoahs",
"mummies",
"canibals",
"50 Cent",
"jet packs",
"kitchen sinks",
"hiding places");

// Briefs
function writeSubjectBrief() {
var randomSubject = subjects[Math.floor(Math.random() * subjects.length)];
var randomSubject2 = subjects[Math.floor(Math.random() * subjects.length)];
var briefier = new Array(
"Come up with a new use for " + randomSubject,
"Draw a mashup between " + randomSubject + " and " + randomSubject2,
"Design a chair for " + randomSubject,
"Come up with a DJ name for " + randomSubject,
"Draw a road hazard sign for " + randomSubject,
"Create the cover for a book about " + randomSubject,
"Invent a dance inspired by " + randomSubject,
"Give a reason why grannies should buy " + randomSubject,
"Create a theme park ride based on " + randomSubject,
"Draw an article of clothing for " + randomSubject,
"Write an ode to " + randomSubject,
"Write the marriage vows for " + randomSubject + " and " + randomSubject2,
"Draw a gravestone for " + randomSubject,
"Draw " + randomSubject + " as a superhero",
"Write a letter of apology from " + randomSubject + " to " + randomSubject2,
"Write a letter of complaint from " + randomSubject + " to " + randomSubject2,
"Create a fast food chain targeting " + randomSubject,
"Create the cover for a concept album about " + randomSubject,
"Draw the blackboard after a lesson about " + randomSubject,
"Draw blueprints for a spaceship powered by " + randomSubject,
"Create a memorial to " + randomSubject,
"What is the meaning of life for " + randomSubject + "?",
"Create a mode of transport for " + randomSubject,
"Create a beach holiday for " + randomSubject,
"Write something that would offend " + randomSubject,
"Write some new years resolutions for " + randomSubject,
"Write the title of a novel about " + randomSubject,
"Create a beauty regime for " + randomSubject,
"Design a piece of clothing for " + randomSubject,
"Write the returns policy for " + randomSubject,
"Name five things you love about " + randomSubject,
"Notice five flaws about " + randomSubject,
"Write a love letter between " + randomSubject + " and " + randomSubject2,
"How would Salvador Dalí draw " + randomSubject,
"Write a chat-up line for " + randomSubject,
"Write the opening to a musical about " + randomSubject,
"Come up with a catchphrase for " + randomSubject,
"Write part of a musical about " + randomSubject,
"What is porn for " + randomSubject + "?",
"How do you flirt with " + randomSubject + "?",
"What are the erogenous zones of " + randomSubject + "?",
"Write the premise for a horror movie about " + randomSubject,
"Write a tweet from " + randomSubject,
"Come up with a B movie about " + randomSubject,
"What is the darkest confession of " + randomSubject + "?",
"Write a tenancy agreement for " + randomSubject + "?",
"Design uniforms for a racist cult against " + randomSubject,
"Design the flag for a nation of " + randomSubject,
"What would 'the " + randomSubject + " scandal' be?",
"What is heaven for " + randomSubject + "?",
"What is hell for " + randomSubject + "?",
"Create a conceptual art exhibition about " + randomSubject,
"How do you get " + randomSubject + " out of your house?",
"What would the policies be if " + randomSubject + " ran for prime minister?",
"How would " + randomSubject + " make " + randomSubject2 + " redundant?");
var randomBrief = briefier[Math.floor(Math.random() * briefier.length)];
window.randomBrief = randomBrief;
$("#brief-card").fadeOut(function() {
$("#gobutton").html('<span class="glyphicon glyphicon-repeat"></span> NEW PROBLEM');
$("#brief").text(randomBrief);
var noq = (briefier.length * subjects.length);
$("#noq").text("you're answering one of " + noq + " possible questions");
Clock.resetPlay();
}).fadeIn();}
